{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.labels }}
  labels:
{{ toYaml $machineClass.labels | indent 4 }}
{{- end }}
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.labels }}
  labels:
  {{ toYaml $machineClass.labels | indent 4 }}
{{- end }}
provider: "OpenStack"
{{- if $machineClass.nodeTemplate }}
nodeTemplate:
  capacity:
{{ toYaml $machineClass.nodeTemplate.capacity | indent 4 }}
  instanceType: {{ $machineClass.nodeTemplate.instanceType }}
  region: {{ $machineClass.nodeTemplate.region }}
  zone: {{ $machineClass.nodeTemplate.zone }}
{{- end }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
credentialsSecretRef:
  name: {{ $machineClass.credentialsSecretRef.name }}
  namespace: {{ $machineClass.credentialsSecretRef.namespace }}
providerSpec:
  apiVersion: openstack.machine.gardener.cloud/v1alpha2
  kind: MachineProviderConfig
  spec:
    region: {{ $machineClass.region }}
    availabilityZone: {{ $machineClass.availabilityZone }}
    flavorName: {{ $machineClass.machineType }}
    keyName: {{ $machineClass.keyName }}
{{- if $machineClass.imageID }}
    imageID: {{ $machineClass.imageID }}
{{- else }}
    imageName: {{ $machineClass.imageName }}
{{- end }}
    network:
      networkID: {{ $machineClass.network.networkID }}
      subnetID: {{ $machineClass.network.subnetID }}
      cidr: {{ $machineClass.network.cidr }}
{{- if $machineClass.additionalNetworks }}
    additionalNetworks:
{{ toYaml $machineClass.additionalNetworks | indent 4 }}
{{- end }}
{{- if $machineClass.rootDiskSize }}
    rootDiskSize: {{ $machineClass.rootDiskSize }}
{{- end }}
{{- if $machineClass.rootDiskType}}
    rootDiskType: {{ $machineClass.rootDiskType }}
{{- end }}
{{- if $machineClass.serverGroupID }}
    serverGroupID: {{ $machineClass.serverGroupID }}
{{- end }}
    securityGroups:
{{ toYaml $machineClass.securityGroups | indent 4 }}
{{- if $machineClass.tags }}
    tags:
{{ toYaml $machineClass.tags | indent 6 }}
{{- end }}
{{- end }}
